swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: /api
schemes: [http, https]

paths:
  /get_token:
    post:
      summary: Returns the secret string.
      operationId: dl_service.get_token_api
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: user
          type: string
          required: true
          default: "user"
          description: Returns the token for the given user.
      responses:
        200:
          description: secret response
          schema:
            type: string
  /list_deployed_models:
    post:
      summary: Returns the list of deployed models.
      operationId: dl_service.list_deployed_models_api
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
      responses:
        200:
          description: List of deployed models is dispayed
          schema:
            type: string
  /deploy:
    post:
      summary: Deploy a machine learning model.
      operationId: dl_service.deploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          default: "mnist_model"
          description: The name of the model to be deployed.
        - in: formData
          name: model_file
          type: file
          required: true
          description: The zip file containing the model that will be deployed.
        - in: formData
          name: model_version
          type: integer
          minimum: 1
          required: false
          allowEmptyValue: true
          description: The version number of the model that will be downloaded and deployed.
        - in: formData
          name: append
          type: boolean
          required: true
          default: true
          description: Append the model to the list of already deployed models.
      responses:
        200:
          description: Model deployed
          schema:
            type: string
  /undeploy_model:
    post:
      summary: Remove a deployed model.
      operationId: dl_service.undeploy_model_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          description: The name of the model to delete.
        - in: formData
          name: model_version
          type: integer
          required: false
          description: The model version to delete.
      responses:
        200:
          description: "Model removed"
          schema:
            type: string
  /redeploy:
    post:
      summary: Redeploy a previous deployed model.
      operationId: dl_service.redeploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          description: The name of the model that will be deployed.
        - in: formData
          name: model_version
          type: string
          required: false
          description: The vesrion of the model that will be deployed.
        - in: formData
          name: append
          type: boolean
          required: true
          default: true
          description: Append the model to the list of already deployed models.
      responses:
        200:
          description: "Model redeployed"
          schema:
            type: string
  /predict:
    post:
      summary: Make predictions
      description: Make predictions from a given dataframe in a JSON format.
      operationId: dl_service.predict_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          default: "mnist_model"
          description: The name of the model that will be used for the prediction.
        - in: formData
          name: model_version
          type: integer
          required: false
          description: The model version that will be used for the prediction.
        - in: formData
          name: image
          type: file
          required: true
          description: The image to be predicted
        - in: formData
          name: class_names
          type: string
          required: true
          default: "T-shirt/top,Trouser,Pullover,Dress,Coat,Sandal,Shirt,Sneaker,Bag,Ankle boot"         
      responses:
        200:
          description: prediction response
          schema:
            type: string
  /download_model_config:
    post:
      summary: Returns the model config used by the Tensorflow model server
      operationId: dl_service.download_model_config_api
      produces:
        - "application/octet-stream"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
      responses:
        200:
          description: The model config file used by Tensorflow model server
          schema:
            type: file
  /upload_model_config:
    post:
      summary: Uploads a new model config that will be used by Tensorflow model server
      operationId: dl_service.upload_model_config_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_config_file
          type: file
          required: true
          description: The model config file that will be used by Tensorflow model server
      responses:
        200:
          description: "Model config file uploaded"
          schema:
            type: string
  /list_saved_models:
    post:
      summary: List saved models in MODELS_PATH repository
      operationId: dl_service.list_saved_models
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: json_response
          type: boolean
          required: true
          default: true
          description: The API token generated for the user.
      responses:
        200:
          description: "List of downloaded models"
          schema:
            type: string
  /clean_saved_models:
    post:
      summary: Delete a specific saved model from the container
      operationId: dl_service.clean_saved_models
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          description: The model_name that need to be deleted.
        - in: formData
          name: model_version
          type: string
          description: The model_version that need to be deleted.
      responses:
        200:
          description: "Model folder deletion status"
          schema:
            type: string
  /trace_preview:
    get:
      summary: Returns the stored traceability information.
      operationId: dl_service.trace_preview_api
      produces:
        - "text/html"
      parameters:
        - in: query
          name: key
          type: string
          required: true
          default: ""
          description: The key generated during the service deployment.
      responses:
        200:
          description: text-like traceability information
          schema:
            type: string
