swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: /api
schemes: [http, https]

paths:
  /get_token:
    post:
      summary: Returns the secret string.
      operationId: ml_service.get_token_api
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: user
          type: string
          required: true
          default: "user"
          description: Returns the token for the given user.
      responses:
        200:
          description: secret response
          schema:
            type: string
  /list_saved_models:
    post:
      summary: Returns the list of saved models.
      operationId: ml_service.list_saved_models_api
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: json_format
          type: boolean
          required: true
          default: true
          description: The format of the result.
      responses:
        200:
          description: json-like list of models
          schema:
            type: string
  /deploy:
    post:
      summary: Deploy a machine learning model.
      operationId: ml_service.deploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          description: The model_name that need to be deployed.
        - in: formData
          name: model_version
          type: string
          description: The model_version that need to be deployed. If this field is not specified, the model version will be computed as following the last_deployed_version of this model_name + 1.
        - in: formData
          name: model_file
          type: file
          required: true
          description: The machine learning model file to be uploaded.
        - in: formData
          name: baseline_data
          type: file
          required: false
          description: The baseline data used for drift detection in the incoming datasets.
        - in: formData
          name: debug_enabled
          type: boolean
          required: false
          default: true
          description: Enable/disable service debugging.
        - in: formData
          name: trace_enabled
          type: boolean
          required: false
          default: true
          description: Enable/disable service traceability.
      responses:
        200:
          description: "Model deployed"
          schema:
            type: string
  /delete_deployed_model:
    post:
      summary: Remove a deployed model.
      operationId: ml_service.delete_deployed_model_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_name
          type: string
          required: true
          description: The model_name that need to be undeployed and deleted.
        - in: formData
          name: model_version
          type: string
          description: The model_version that need to be undeployed and deleted. If this field is not specified, all the versions associated to the specified model_name will be deleted
      responses:
        200:
          description: "Model removed"
          schema:
            type: string
  /update:
    post:
      summary: Update service parameters.
      operationId: ml_service.update_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: debug_enabled
          type: boolean
          required: true
          default: true
          description: Enable/disable service debugging.
        - in: formData
          name: trace_enabled
          type: boolean
          required: true
          default: true
          description: Enable/disable service traceability.
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
      responses:
        200:
          description: "Service parameters updated"
          schema:
            type: string
  /predict:
    post:
      summary: Make predictions
      description: Make predictions from a given dataframe in a JSON format.
      operationId: ml_service.predict_api
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: json-like prediction response
          schema:
            type: string
          examples:
            "application/json": "[2 2 0]"
      parameters:
        - in: body
          name: data
          description: The data to be sent to the predict api.
          schema:
            type: object
            required:
              - api_token
              - predict_dataframe_json
              - detector
              - model_name
              - model_version
            properties:
              api_token:
                type: string
                default: "376d873c859d7f9f268e1b9be883745b"
              model_name:
                type: string
                default: "iris_flowers_classifier"
              model_version:
                type: integer
                default: 1
              predict_dataframe_json:
                type: string
                default: "[[6.5,3.0,5.5,1.8],[6.1,3.0,4.9,1.8],[4.8,3.0,1.4,0.1]]"
              detector:
                type: string
                default: "HDDM"
              save_predictions:
                type: boolean
                default: false
              drift_enabled:
                type: boolean
                default: false
              drift_notification:
                type: boolean
                default: false
#  /predictions_preview:
#    get:
#      summary: Returns the stored predictions.
#      operationId: ml_service.predictions_preview_api
#      produces:
#        - "text/html"
#      parameters:
#        - in: query
#          name: key
#          type: string
#          required: true
#          default: ""
#          description: The key generated during the service deployment.
#      responses:
#        200:
#          description: text-like predictions information
#          schema:
#            type: string
  /trace_preview:
    get:
      summary: Returns the stored traceability information.
      operationId: ml_service.trace_preview_api
      produces:
        - "text/html"
      parameters:
        - in: query
          name: key
          type: string
          required: true
          default: ""
          description: The key generated during the service deployment.
      responses:
        200:
          description: text-like traceability information
          schema:
            type: string
