swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: /api
schemes: [http, https]

paths:
  /get_token:
    post:
      summary: Return secret string
      operationId: ml_service.get_token_api
      produces:
        - "text/plain"
      responses:
        200:
          description: secret response
          schema:
            type: string
      parameters:
        - in: formData
          name: user
          type: string
          required: true
          default: "user"
          description: Returns the token for the user.
  /deploy:
    post:
      summary: Deploy a machine learning model.
      operationId: ml_service.deploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      responses:
        200:
          description: deployment response
          schema:
            type: string
      parameters:
        - in: formData
          name: modelfile
          type: file
          required: true
          description: The machine learning model file to upload.
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token to be sent to the deploy api.
      responses:
        200:
          description: "Model updated"
  /predict:
    post:
      summary: Generate predictions
      description: Generate predictions from a given dataframe in a JSON format.
      operationId: ml_service.predict_api
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: prediction response
          schema:
            type: string
          examples:
            "application/json": "[2 2 0]"
      parameters:
        - in: body
          name: data
          description: The data to be sent to the predict api.
          schema:
            type: object
            required:
              - dataframe_json
              - api_token
            properties:
              dataframe_json:
                type: string
                default: "[[6.5,3.0,5.5,1.8],[6.1,3.0,4.9,1.8],[4.8,3.0,1.4,0.1]]"
              api_token:
                type: string
                default: "376d873c859d7f9f268e1b9be883745b"