swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: /api
schemes: [http, https]

paths:
  /get_token:
    post:
      summary: Returns the secret string.
      operationId: ml_service.get_token_api
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: user
          type: string
          required: true
          default: "user"
          description: Returns the token for the given user.
      responses:
        200:
          description: secret response
          schema:
            type: string
  /list_models:
    post:
      summary: Returns the list of deployed models.
      operationId: ml_service.list_models_api
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
      responses:
        200:
          description: json-like list of models
          schema:
            type: string
  /deploy:
    post:
      summary: Deploy a machine learning model.
      operationId: ml_service.deploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      parameters:
        - in: formData
          name: model_file
          type: file
          required: true
          description: The machine learning model file to be uploaded.
        - in: formData
          name: model_metadata_json
          type: string
          required: false
          default: "[[5.8216666667,3.0658333333,3.695,1.1766666667],[0.8128364419,0.4385797999,1.7614380107,0.7581194484]]"
          description: The metadata associated to the model.
        - in: formData
          name: debug_enabled
          type: boolean
          required: false
          default: true
          description: Enable/disable service debugging.
        - in: formData
          name: trace_enabled
          type: boolean
          required: false
          default: true
          description: Enable/disable service traceability.
        - in: formData
          name: drift_enabled
          type: boolean
          required: false
          default: true
          description: Enable/disable the data drift detection mechanism.
        - in: formData
          name: drift_threshold
          type: number
          required: false
          default: 1.9
          description: Set the data drift treshold.
        - in: formData
          name: drift_notification
          type: boolean
          required: false
          default: true
          description: Enable/disable the data drift notification mechanism.
        - in: formData
          name: log_predictions
          type: boolean
          required: false
          default: true
          description: Enable/disable the prediction logging.
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
      responses:
        200:
          description: "Model updated"
          schema:
            type: string
  /undeploy:
    post:
      summary: Remove a deployed model.
      operationId: ml_service.undeploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_file
          type: string
          required: true
          default: "/model_as_a_service/model_last.model"
          description: The model file to delete.
      responses:
        200:
          description: "Model removed"
          schema:
            type: string
  /redeploy:
    post:
      summary: Redeploy a previous deployed model.
      operationId: ml_service.redeploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "text/plain"
      parameters:
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token generated for the user.
        - in: formData
          name: model_file
          type: string
          required: true
          description: The model file to be deployed.
      responses:
        200:
          description: "Model deployed"
          schema:
            type: string
  /predict:
    post:
      summary: Make predictions
      description: Make predictions from a given dataframe in a JSON format.
      operationId: ml_service.predict_api
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: json-like prediction response
          schema:
            type: string
          examples:
            "application/json": "[2 2 0]"
      parameters:
        - in: body
          name: data
          description: The data to be sent to the predict api.
          schema:
            type: object
            required:
              - dataframe_json
              - api_token
            properties:
              dataframe_json:
                type: string
                default: "[[6.5,3.0,5.5,1.8],[6.1,3.0,4.9,1.8],[4.8,3.0,1.4,0.1]]"
              api_token:
                type: string
                default: "376d873c859d7f9f268e1b9be883745b"
  /predictions_preview:
    get:
      summary: Returns the stored predictions.
      operationId: ml_service.predictions_preview_api
      produces:
      #  - "text/plain"
        - "text/html"
      parameters:
        - in: query
          name: key
          type: string
          required: true
          default: ""
          description: The key generated during the service deployment.
      responses:
        200:
          description: text-like predictions information
          schema:
            type: string
  /trace_preview:
    get:
      summary: Returns the stored traceability information.
      operationId: ml_service.trace_preview_api
      produces:
      #  - "text/plain"
        - "text/html"
      parameters:
        - in: query
          name: key
          type: string
          required: true
          default: ""
          description: The key generated during the service deployment.
      responses:
        200:
          description: text-like traceability information
          schema:
            type: string
  #/trace:
  #  post:
  #    summary: Returns the stored traceability information.
  #    operationId: ml_service.trace_api
  #    produces:
  #      - "text/plain"
  #    parameters:
  #      - in: formData
  #        name: api_token
  #        type: string
  #        required: true
  #        default: "376d873c859d7f9f268e1b9be883745b"
  #        description: The API token generated for the user.
  #    responses:
  #      200:
  #        description: text-like traceability information
  #        schema:
  #          type: string
  #/test_workflow_submission:
  #  post:
  #    summary: Test the workflow submission mechanism.
  #    operationId: ml_service.test_workflow_submission_api
  #    produces:
  #      - "text/plain"
  #    parameters:
  #      - in: formData
  #        name: api_token
  #        type: string
  #        required: true
  #        default: "376d873c859d7f9f268e1b9be883745b"
  #        description: The API token generated for the user.
  #    responses:
  #      200:
  #        description: text-like workflow submission test
  #        schema:
  #          type: string
  #/test_web_notification:
  #  post:
  #    summary: Test the web notification mechanism.
  #    operationId: ml_service.test_web_notification_api
  #    produces:
  #      - "text/plain"
  #    parameters:
  #      - in: formData
  #        name: api_token
  #        type: string
  #        required: true
  #        default: "376d873c859d7f9f268e1b9be883745b"
  #        description: The API token generated for the user.
  #    responses:
  #      200:
  #        description: text-like web notification test
  #        schema:
  #          type: string
